# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Messenger ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido')),
                ('profile_pic', models.CharField(blank=True, max_length=500, null=True, verbose_name='Foto de Perfil')),
                ('locale', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lugar')),
                ('timezone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Zona Horaria')),
                ('gender', models.CharField(blank=True, max_length=150, null=True, verbose_name='Género')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_info', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'verbose_name': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='MessengerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Token')),
                ('psid', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='PSID')),
                ('page_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='PAGE ID')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_session', to='messenger.MessengerInfo', verbose_name='Información del usuario')),
            ],
            options={
                'verbose_name_plural': 'Sesiones de Messenger',
                'verbose_name': 'Sesion de Messenger',
            },
        ),
    ]
