# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Repuesta')),
            ],
            options={
                'verbose_name_plural': 'Respuestas',
                'verbose_name': 'Respuesta',
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(to='messenger.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
                'verbose_name': 'Pregunta',
            },
        ),
        migrations.AddField(
            model_name='intent',
            name='question',
            field=models.ManyToManyField(to='messenger.Question'),
        ),
    ]
